server:
  port: 8181

Inditex:
    prices:
        version: 1
        
spring:
  h2:
    console: 
        enabled: true
        path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
        ddl-auto: update
    properties:
      hibernate.format_sql: false
      #hibernate.jdbc.time_zone: UTC
        

      